-- Run once to populate tbl_mappings from hardcoded mappings.
-- INSERT ... ON CONFLICT DO NOTHING so safe to run multiple times.

-- VW (tbl_vworkjobs)
INSERT INTO tbl_mappings (type, filefieldname, dbcolumnname, dbmaxlength) VALUES
('VW', 'job id', 'job_id', 20),
('VW', 'client name', 'customer', 100),
('VW', 'when', 'planned_start_time', NULL),
('VW', 'planned start (d/m/y)', 'planned_start_time', NULL),
('VW', 'planned duration (hrs)', 'planned_duration_mins', NULL),
('VW', 'planned duration (mins)', 'planned_duration_mins', NULL),
('VW', 'gps start time', 'gps_start_time', NULL),
('VW', 'gps end time', 'gps_end_time', NULL),
('VW', 'gps duration (mins)', 'gps_duration_mins', NULL),
('VW', 'proof of delivery', 'proof_of_delivery', 100),
('VW', 'progress of job', 'progress_state', 50),
('VW', 'progress state', 'progress_state', 50),
('VW', 'number of days', 'number_of_steps', NULL),
('VW', 'number of steps', 'number_of_steps', NULL),
('VW', 'signed by', 'worker', 50),
('VW', 'step 1 planner', 'step_1_name', 100),
('VW', 'step 1 name', 'step_1_name', 100),
('VW', 'step 1 completed at', 'step_1_completed_at', NULL),
('VW', 'step 1 address', 'step_1_address', 500),
('VW', 'step 2 planner', 'step_2_name', 100),
('VW', 'step 2 name', 'step_2_name', 100),
('VW', 'step 2 completed at', 'step_2_completed_at', NULL),
('VW', 'step 2 address', 'step_2_address', 500),
('VW', 'step 3 planner', 'step_3_name', 100),
('VW', 'step 3 name', 'step_3_name', 100),
('VW', 'step 3 completed at', 'step_3_completed_at', NULL),
('VW', 'step 3 address', 'step_3_address', 500),
('VW', 'step 4 planner', 'step_4_name', 100),
('VW', 'step 4 name', 'step_4_name', 100),
('VW', 'step 4 completed at', 'step_4_completed_at', NULL),
('VW', 'step 4 address', 'step_4_address', 500),
('VW', 'audit_id', 'booking_id', NULL),
('VW', 'bookingid', 'booking_id', NULL),
('VW', 'container mod', 'contains_mog', 50),
('VW', 'contains mog', 'contains_mog', 50),
('VW', 'delivery location (map)', 'delivery_location_map', 500),
('VW', 'delivery location map', 'delivery_location_map', 500),
('VW', 'delivery (when)', 'delivery_winery', 200),
('VW', 'delivery winery', 'delivery_winery', 200),
('VW', 'joblaml', 'comments', 1000),
('VW', 'driver notes', 'driver_notes', 1000),
('VW', 'help docket number', 'field_docket_number', 50),
('VW', 'field docket number', 'field_docket_number', 50),
('VW', 'pickup location (map)', 'pickup_location_map', 500),
('VW', 'pickup location map', 'pickup_location_map', 500),
('VW', 'further reqs', 'field_notes', 1000),
('VW', 'field notes', 'field_notes', 1000),
('VW', 'comments', 'comments', 1000),
('VW', 'vinename', 'vinename', 100),
('VW', 'load size', 'load_size', NULL),
('VW', 'number of loads', 'number_of_loads', NULL),
('VW', 'trailer rego', 'trailer_rego', 20),
('VW', 'truck id', 'truck_id', 20),
('VW', 'truck rego', 'truck_rego', 20),
('VW', 'template', 'template', 50),
('VW', 'worker', 'worker', 50),
('VW', 'worker duration (mins)', 'worker_duration_mins', NULL)
ON CONFLICT (type, filefieldname) DO NOTHING;

-- GPS (tbl_gpsdata)
INSERT INTO tbl_mappings (type, filefieldname, dbcolumnname, dbmaxlength) VALUES
('GPS', 'no.', 'no', NULL),
('GPS', 'no', 'no', NULL),
('GPS', 'evice nam', 'device_name', 50),
('GPS', 'device name', 'device_name', 50),
('GPS', 'imei', 'imei', 50),
('GPS', 'model', 'model', 50),
('GPS', 'driver name', 'driver_name', 50),
('GPS', 'number plate', 'number_plate', 50),
('GPS', 'sim', 'sim', 50),
('GPS', 'phone', 'phone', 50),
('GPS', 'ence nam', 'fence_name', 150),
('GPS', 'fence name', 'fence_name', 150),
('GPS', 'enter time', 'enter_time', NULL),
('GPS', 'outer time', 'outer_time', NULL),
('GPS', 'out time', 'outer_time', NULL),
('GPS', 'exit time', 'outer_time', NULL),
('GPS', 'stay time', 'stay_time', NULL)
ON CONFLICT (type, filefieldname) DO NOTHING;
